### ISSUE TITLE
VIEW DEMO NOW - link broken

### ISSUE THREAD

**Issue by rfink** [chrisjpowers/business-rules#5]
Takes me to a 404 page

**Comment by jimmysawczuk** [comment]
:+1:

**Comment by aravindvelandi** [comment]
Any chance the demo link is coming back?

**Comment by chrisjpowers** [comment]
Sorry everyone, the demo was lost when I overhauled my blog. [It's now back up](http://chrisjpowers.com/business-rules/) at the original URL.
